#The dataset is found here: https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification?resource=download

In [2]:
#Importing libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [14]:
#Importing the dataset
dataset = pd.read_csv('Data/features_30_sec.csv')
print('No. of rows: ' + str(len(dataset)))
dataset.head()

No. of rows: 1000


filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0  blues.00000.wav  661794          0.350088         0.088757  0.130228   
1  blues.00001.wav  661794          0.340914         0.094980  0.095948   
2  blues.00002.wav  661794          0.363637         0.085275  0.175570   
3  blues.00003.wav  661794          0.404785         0.093999  0.141093   
4  blues.00004.wav  661794          0.308526         0.087841  0.091529   

    rms_var  spectral_centroid_mean  spectral_centroid_var  \
0  0.002827             1784.165850          129774.064525   
1  0.002373             1530.176679          375850.073649   
2  0.002746             1552.811865          156467.643368   
3  0.006346             1070.106615          184355.942417   
4  0.002303             1835.004266          343399.939274   

   spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0              2002.449060            85882.761315  ...   52.420910   
1              2039.036516           213843.755497  ...   55.356403   
2              1747.702312            76254.192257  ...   40.598766   
3              1596.412872           166441.494769  ...   44.427753   
4              1748.172116            88445.209036  ...   86.099236   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0    -1.690215   36.524071    -0.408979   41.597103    -2.303523   55.062923   
1    -0.731125   60.314529     0.295073   48.120598    -0.283518   51.106190   
2    -7.729093   47.639427    -1.816407   52.382141    -3.439720   46.639660   
3    -3.319597   50.206673     0.636965   37.319130    -0.619121   37.259739   
4    -5.454034   75.269707    -0.916874   53.613918    -4.404827   62.910812   

   mfcc20_mean  mfcc20_var  label  
0     1.221291   46.936035  blues  
1     0.531217   45.786282  blues  
2    -2.231258   30.573025  blues  
3    -3.407448   31.949339  blues  
4   -11.703234   55.195160  blues  

[5 rows x 60 columns]

In [11]:
#Splitting the data
X = dataset.iloc[:,2:59]
Y = dataset.iloc[:,59]
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state=0, test_size=0.2)

In [12]:
# Scaling all the features
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.transform(x_test)


In [15]:
# Getting the value of K
import math
math.sqrt(len(x_train))

28.284271247461902

In [17]:
# Making the classifier and getting predictions
knn_classifier = KNeighborsClassifier(n_neighbors=27, p = 2, metric='euclidean')
knn_classifier.fit(x_train, y_train)

#Getting predictions on test data
y_pred = knn_classifier.predict(x_test)

KNeighborsClassifier(metric='euclidean', n_neighbors=27)

In [18]:
# Getting the model's confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[12  0  1  0  0  0  0  0  1  1]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 1  1 19  3  0  1  0  0  0  2]
 [ 0  0  3 17  1  0  1  0  0  0]
 [ 0  0  1  7  6  0  1  1  6  1]
 [ 0  2  3  3  0  9  0  0  1  0]
 [ 1  0  1  1  0  0 16  0  1  0]
 [ 0  0  1  1  0  0  0 20  1  1]
 [ 1  0  1  0  2  0  0  4  7  0]
 [ 0  0  5  8  0  2  0  0  0 10]]


In [19]:
#Evaluating the F1 score
print('F1 score: ' + str(f1_score(y_test, y_pred)))

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [20]:
#Displaying the accuracy
print('Accuracy: ' + str(accuracy_score(y_test, y_pred)))

F1 score: 0.635
